### ISSUE TITLE
Rewrite using Vue

### ISSUE THREAD

**Issue by SecretAgent55** [ScratchAddons/website-v2#187]
So basically, I thought it would be nice to rewrite the website in Vue and Vite. It would add the interactive to make it more engaging like a chat or support button at the bottom corner. This is just an idea, and you don't have to implement this.

**Comment by Hans5958** [comment]
I heard people inside our org wanted to do a rewrite, but I think it's just an thought. Anyone is up for this, if they wanted to maintain it. Building this with Hugo is already a large undertaking IMO. 

For now, with this scale, I don't think it is worth the hassle to implement it in these kinds of open-source website. I will close this, but keep in mind that anyone could take over and do something bigger than this.

About the chat box, I think this is the one that is we either (a) don't have the resources or (b) don't want to implemented because (ba) we already got Discord or (bb) we don't want additional cookies to be on the website. I don't know, but we are searching for a way for better implementation. Either way, using a framework is quite unnecessary to implement this feature.

**Comment by Secret-chest** [comment]
What aboit using Jekyll?

**Comment by WorldLanguages** [comment]
JavaScript frameworks aren't necessary for our use case.

**Comment by Hans5958** [comment]
> What aboit using Jekyll?

That's one step backwards, my friend.
