### ISSUE TITLE
Make the install link on the website header bar styled other than a hovered link

### ISSUE THREAD

**Issue by penguinmoose** [ScratchAddons/website-v2#244]
**Problem**

Right now, the “install” button/link on the website header bar is styled exactly like a hovered link on the header. This makes it look as if it’s hovered upon and is indistinguishable from a hovered link. This makes the header look a bit confusing when a link is hovered upon.

**Proposed solution**

To solve this problem, I think it would be good to make the color and styling of the install button/link in the website header something other than the color and styling of a hovered link. This can be done by changing the background color of the install button to another color. Alternatively, there can be a white border around the install button/link (credit to @Hans5958 for suggestion). There might also be spacing between the install button and the other links.

**Alternatives**

- Instead of changing the install button/link, the styling and color of a hovered link in the header can be changed.

Note: I can make a PR.

**Comment by Hans5958** [comment]
To be fair, I won't change it to light orange due to the fact that that orange and white is not contrast enough on ARIA standards, and making it light orange wouldn't be better.

I would prefer a better idea to just change the install button style instead. Does this good to you?

![image](https://user-images.githubusercontent.com/11584103/185943413-c88cb1ab-3cf1-42e2-9e2e-729fb3a4b6b1.png)

**Comment by penguinmoose** [comment]
@Hans5958 That actually looks great! In fact, that's how most of these things are styled on other websites.

**Comment by penguinmoose** [comment]
Created PR - #246

**Comment by Hans5958** [comment]
Resolved in 06fa0fce1f4f21030c74b0defa188d0cfcdf2793
