### ISSUE TITLE
Merge refrence and development docs

### ISSUE THREAD

**Issue by Samq64** [ScratchAddons/website-v2#324]
I think the reference and development documentation categories should be merged into one since everything there is all related to development except the design page.

**Comment by Hans5958** [comment]
Both parts are separated because both of them have different purposes (at least a little). "Developing" contains guides, rules, and other general documentation related to the Scratch Addon's development. "References" contains more depth documentation related to parts of Scratch Addons. Think both of it as a general book on learning a language, and a dictionary.
