### ISSUE TITLE
Yanked -> Unreleased

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/website-v2#72]
"Yanked" versions aren't actually yanked; they are not released at all.

**Comment by mxmou** [comment]
Wasn't 1.1.0 released on Firefox?

**Comment by Hans5958** [comment]
In the basis of changelogs, the term of **Unreleased** is for something that wasn't released yet, but will be released in the future. The good example is that if we wish to put the changelog posts you made on Discussions on CHANGELOG.md, it will be put in a heading of **Unreleased**. So, the term **Unreleased** is conflicting with the current understanding, so we need a good alternative, if we wish to change it.

Also, the term **Yanked** is already agreed upon on olivierlacan/keep-a-changelog, so I'll go with it since it is an adopted standard and I don't want people to become confused with it.

- olivierlacan/keep-a-changelog#35
- olivierlacan/keep-a-changelog#252

Some examples are withdrawn, obsolete, nuked, removed, etc.

But for now, I think the term **Yanked** is fine for now.
